services:
  postgres_exporter_koda:
    image: prometheuscommunity/postgres-exporter:v0.20.1@sha256:ac5ec343104fae0e2d84a27bb8d69b38430a11910c5382cad85d478d2bab713e
    container_name: monitoring_postgres_koda
    restart: unless-stopped
    env_file:
      - ./exporters/koda/.env.postgres_exporter
    networks:
      - koda_network
      - monitoring_network
    labels:
      project: "koda"
      service: "postgres"

  redis_exporter_koda:
    image: oliver006/redis_exporter:v1.93.0@sha256:6ca518a72f30f7f576ef92963de1b91d3c3f5fd3aeac949f878bfda183587820
    container_name: monitoring_redis_koda
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis://koda_redis:6379"
    networks:
      - koda_network
      - monitoring_network
    labels:
      project: "koda"
      service: "redis"

  nginx_exporter_koda:
    image: nginx/nginx-prometheus-exporter:1.1.0@sha256:d710e0ff2505a7037dd21e47eae07025010c0de08a6247d1a704824823becfd0
    container_name: monitoring_nginx_koda
    restart: unless-stopped
    command:
      - "--nginx.scrape-uri=http://koda_nginx/nginx_status"
    networks:
      - koda_network
      - monitoring_network
    labels:
      project: "koda"
      service: "nginx"

networks:
  koda_network:
    external: true
  monitoring_network: {}
