services:
  postgres_exporter_koda:
    image: prometheuscommunity/postgres-exporter:v0.20.1@sha256:ac5ec343104fae0e2d84a27bb8d69b38430a11910c5382cad85d478d2bab713e
    container_name: monitoring_postgres_koda
    restart: unless-stopped
    env_file:
      - ./exporters/koda/.env.postgres_exporter
    networks:
      - koda_network
      - monitoring_network
    labels:
      project: "koda"
      service: "postgres"

  redis_exporter_koda:
    image: oliver006/redis_exporter:v1.92.1@sha256:7fbc93d30f0f91eed1b2fe6968a956259cc5d260a984dd9071f1d1e9c2692ecd
    container_name: monitoring_redis_koda
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis://koda_redis:6379"
    networks:
      - koda_network
      - monitoring_network
    labels:
      project: "koda"
      service: "redis"

  nginx_exporter_koda:
    image: nginx/nginx-prometheus-exporter:1.5.3@sha256:85666e7fde7e253f1c6d978f9a961245df4c9cdb7677e1866d9bb28e8f9ee41d
    container_name: monitoring_nginx_koda
    restart: unless-stopped
    command:
      - "--nginx.scrape-uri=http://koda_nginx/nginx_status"
    networks:
      - koda_network
      - monitoring_network
    labels:
      project: "koda"
      service: "nginx"

networks:
  koda_network:
    external: true
  monitoring_network: {}
